### ISSUE TITLE
[Enhancement] Pokeapi

### ISSUE THREAD

**Issue by freitagdavid** [RichardPaulAstley/richardpaulastley.github.io#25]
So I took a quick look at the source code and it would seem that you are either hard coding or using a data dump for pokemon data have you though of the possibility of pulling the data dynamically from pokeapi. The only stipulation is that you have to cache the resources on the client computer but it would be much easier than trying to hand input all the data.

**Comment by RichardPaulAstley** [comment]
Hey !

So, to answer, yes beofre I was adding everything myself, aka with my hands and looking on differents sites. That's why Jotho and cie were slow to come.

But Fastigium wanted to help me with that, and imported ALL the data using something like pokeapi, using datas from pokemondb.net (that's why credits are there with sprites) so now, it's really done, and all Pokemon are here (to Volcanion, 7G is not available, and I need to find time how i'll implement them in fact) 

So don't worry, the injection in bulk has been done already, you can check here : https://github.com/RichardPaulAstley/richardpaulastley.github.io/commit/717600b9907fc1ed9e57ba2d95195043c103ffa7 to see the change haha

Thank you so much for the tip o/
