### ISSUE TITLE
Can the game be account based?

### ISSUE THREAD

**Issue by MHketbi** [RichardPaulAstley/richardpaulastley.github.io#6]
hello,

do you think you will be able to make the game account based where our progress is saved per account?

helps when we use more than one PC.

**Comment by RichardPaulAstley** [comment]
Hi,

This one is not even about being able to do it, it's no. Doing that means creating database, so not being able to host it for free, and if the game would be popular, it'd be CRAZY amount to pay for it every month, and so i'd have to start to spam with donations and advertisments. Not my thing.

BUT. I'd like to put a save system like Pokeclickers. This way we could have a little .sav file or something like that in order to keep progress and being able to move it from PC to PC (have the same problem with my 4 computers)

Thanks !
