### ISSUE TITLE
Minify js files

### ISSUE THREAD

**Issue by renlok** [RichardPaulAstley/richardpaulastley.github.io#60]
If speed is the goal why not minify the js files into a single file. It should increase load times and potentially also decrease the memory usage

**Comment by RichardPaulAstley** [comment]
Heyah !

Nice to see you back here o/ ! Hope you're fine !

So well, we talked about this, but I guess this would be harder to make edits on it, since i use it a lot (for editing routes for events, or for adding Pokemon in the database in the future)

If we could find a way to make it light and easier to keep updated, it'd be awesome !

**Comment by renlok** [comment]
You can use something like gulp to automate the process, or you could separate the event code into its own file and leave that as the only thing not compressed so its easy to edit still
