### ISSUE TITLE
Infinite Heal Glitch

### ISSUE THREAD

**Issue by piiih** [RichardPaulAstley/richardpaulastley.github.io#8]
Hi,
One glitch that I found is that the page refresh heal the pokemon, and experience keeps the same.

I was working on a refactoring of this game. I already seprated routes, player actions, and some other things to single files. I'll do a PR with that changes, but I need to merge your updated db first.

:D

**Comment by RichardPaulAstley** [comment]
Hi !

I saw that... I'm not sure if this can be an issue. I'm using it as an auto-healer for training a pokemon during the night in fact, but well !

Wow amazing, want to see that in the future ! But the thing is that i've started the 2G on my database (at least the style the database is done) so i'll look into this.

Could I join you for some help about two things ? I need some help for the auto-ordering pokemon AND having a catch rate for every Pokemon (because in fact, the game doesn't read the catch rate, so every Pokemon has the same probability)

Thanks !

**Comment by piiih** [comment]
Of course, I'll be happy to help you.

**Comment by RichardPaulAstley** [comment]
Thank you so much ! Any way to talk with you ? Like Discord or mail ? 

Thanks !

**Comment by piiih** [comment]
piih_@live.com, I need to create a discord, when I do that I'll send to you.
:)

**Comment by RichardPaulAstley** [comment]
Awesome, contacted you. Closing this right now !
